**240840116036**   

**Practical - 02**

  **Aim : Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas**

**Step - 01 : Import Pandas Library**

In [ ]:
#Import the Pandas library
import pandas as pd

**Step - 02 : Create the Dataset**

In [ ]:
#Create sample data using a dictionary
data = {
    "ID": [1, 2, 3, 4, 5, 6, 7],
    "Name": ["Priya", "Amit", None, "Riya", "Ajay", "Vijay", "Jeni"],
    "Marks": [21.0, None, 20.0, 20.0, 22.0, 23.0, 28.0],
    "City": ["Surat", "Navsari", "Surat", "Bhavnagar", "Bharuch", None, None],
    "Age": [25, None, 5, 8, 7, None, None]
}

**Step-3: Create DataFrame**

In [ ]:
#Convert dictionary into DataFrame
df = pd.DataFrame(data)

**Step-4: Display the Dataset**

In [ ]:
#Display the complete dataset
print(df)

   ID   Name  Marks       City   Age
0   1  Priya   21.0      Surat  25.0
1   2   Amit    NaN    Navsari   NaN
2   3   None   20.0      Surat   5.0
3   4   Riya   20.0  Bhavnagar   8.0
4   5   Ajay   22.0    Bharuch   7.0
5   6  Vijay   23.0       None   NaN
6   7   Jeni   28.0       None   NaN

Step-5: Display First Five Rows

In [ ]:
#Display first five rows
df.head()

   ID   Name  Marks       City   Age
0   1  Priya   21.0      Surat  25.0
1   2   Amit    NaN    Navsari   NaN
2   3   None   20.0      Surat   5.0
3   4   Riya   20.0  Bhavnagar   8.0
4   5   Ajay   22.0    Bharuch   7.0

**Step-6: Display Last Five Rows**

In [ ]:
#Display last five rows
df.tail()

   ID   Name  Marks       City  Age
2   3   None   20.0      Surat  5.0
3   4   Riya   20.0  Bhavnagar  8.0
4   5   Ajay   22.0    Bharuch  7.0
5   6  Vijay   23.0       None  NaN
6   7   Jeni   28.0       None  NaN

**Step-7: Display Dataset Information**

In [ ]:
#Display information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    6 non-null      object
 2   Marks   6 non-null      float64
 3   City    5 non-null      object
 4   Age     4 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 412.0+ bytes

**Step-8: Display Statistical Information**

In [ ]:
#Display statistical summary
df.describe()

             ID      Marks        Age
count  7.000000   6.000000   4.000000
mean   4.000000  22.333333  11.250000
std    2.160247   3.011091   9.251126
min    1.000000  20.000000   5.000000
25%    2.500000  20.250000   6.500000
50%    4.000000  21.500000   7.500000
75%    5.500000  22.750000  12.250000
max    7.000000  28.000000  25.000000

**Step-9: Display Shape of Dataset**

In [ ]:
#Display number of rows and columns
df.shape

(7, 5)

**Step-10: Display Column Names**

In [ ]:
#Display column names
df.columns

Index(['ID', 'Name', 'Marks', 'City', 'Age'], dtype='object')

**Step-11: Display Data Types**

In [ ]:
#Display data type of each column
df.dtypes

ID         int64
Name      object
Marks    float64
City      object
Age      float64
dtype: object

**Step-12: Check Missing Values**

In [ ]:
#Count missing values in each column
df.isnull().sum()

ID       0
Name     1
Marks    1
City     2
Age      3
dtype: int64

**Step-13: Fill Missing Values in Marks**

In [ ]:
#Replace missing marks with average marks
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

**Step-14: Fill Missing Values in Age**

In [ ]:
#Replace missing age with average age
df["Age"] = df["Age"].fillna(df["Age"].mean())

**Step-15: Fill Missing Names**

In [ ]:
#Replace missing names with "Unknown"
df["Name"] = df["Name"].fillna("Unknown")

**Step 16: Fill Missing City**

In [ ]:
#Replace missing city with "Unknown"
df["City"] = df["City"].fillna("Unknown")

**Step 17: Check Duplicate Rows**

In [ ]:
#Check duplicate records
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

**Step 18: Count Duplicate Rows**

In [ ]:
#Count duplicate rows
df.duplicated().sum()

np.int64(0)

**Step 19: Remove Duplicate Rows**

In [ ]:
#Remove duplicate records
df = df.drop_duplicates()

**Step 20: Rename Column**

In [ ]:
#Rename Marks column to Score
df.rename(columns={"Marks":"Score"}, inplace=True)

**Step 21: Change Data Type**

In [ ]:
#Convert Age column to integer
df["Age"] = df["Age"].astype(int)

**Step 22: Create New Column**

In [ ]:
#Create FinalScore column
df["FinalScore"] = df["Score"] + 5

**Step 23: Convert Names to Uppercase**

In [ ]:
#Convert names to uppercase
df["Name"] = df["Name"].str.upper()

**Step 24: Convert City to Lowercase**

In [ ]:
#Convert city names to lowercase
df["City"] = df["City"].str.lower()

**Step 25: Remove Extra Spaces**

In [ ]:
#Remove leading and trailing spaces
df["City"] = df["City"].str.strip()

**Step 26: Sort the Dataset**

In [ ]:
#Sort by FinalScore in descending order
df = df.sort_values(by="FinalScore", ascending=False)

**Step 27: Save the Cleaned Dataset**

In [ ]:
#Save the cleaned dataset to CSV
df.to_csv("cleaned_students.csv", index=False)

**Step 28: Display Final Dataset**

In [ ]:
#Display the cleaned dataset
print(df)

   ID     Name      Score       City  Age  FinalScore
6   7     JENI  28.000000    unknown   11   33.000000
5   6    VIJAY  23.000000    unknown   11   28.000000
1   2     AMIT  22.333333    navsari   11   27.333333
4   5     AJAY  22.000000    bharuch    7   27.000000
0   1    PRIYA  21.000000      surat   25   26.000000
2   3  UNKNOWN  20.000000      surat    5   25.000000
3   4     RIYA  20.000000  bhavnagar    8   25.000000