**240840116036**

**Practical - 01**

**Aim : Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON ƒles using Pandas.**

**Step - 01 : Import the pandas library.**

In [ ]:
#First import the pandas to perform Data Analytics

import pandas as pd

**Step - 02 : Create sample data.**

In [ ]:
#Get/Create a Data on which we will perform practical.

data = {
                "ID" : [101, 102, 103, 104, 105, 106],
                "Name" : ["Rahul", "Priya", "Rajan", "Krisha", "Ruchi", "Dhruvil"],
                "Age" : [20, 21, 13, 20, 22, 20],
                "City" : ["Surat", "Ahemdabad", "Surat", "Vadodara", "Gandhinagar", "Surat"],
                "Marks" : [89, 95, 75, 84, 96, 74]
}

**Step - 03 : Create a Dataframe.**

In [ ]:
#Create a DataFrame to organise the data.

df = pd.DataFrame(data)

df

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  102    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

**Step - 04 : Save Data as a CSV File.**

In [ ]:
#Save the data in csv file format.

df.to_csv("students.csv", index=False)

print("CSV file created successfully.")

CSV file created successfully.

**Step - 05 : Save Data as an Excel File.**

In [ ]:
#Save data in excel file format.

df.to_excel("students.xlsx", index=False)

print("Excel file is created successfully.")

Excel file is created successfully.

**Step - 06 : Save Data as a JSON File.**

In [ ]:
#Save data in JSON file format.

df.to_json("students.json", orient="records", index=4)

print("JSON file is created successfully.")

JSON file is created successfully.

**Step - 07 : Read the CSV File.**

In [ ]:
#Read/Print the csv file.

df_csv = pd.read_csv("students.csv")
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  102    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

**Step - 08 : Read the Excel File.**

In [ ]:
#Read/Print the excel file.

df_excel = pd.read_excel("students.xlsx")
df_excel

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  102    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

**Step - 09 : Read the JSON File.**

In [ ]:
#Read/Print the JSON file.

df_json = pd.read_json("students.json")
df_json

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  102    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

**Step - 10 : Display the First Five Records.**

In [ ]:
#Using head() to print the first five records.

df_csv.head()

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     89
1  102   Priya   21    Ahemdabad     95
2  103   Rajan   13        Surat     75
3  104  Krisha   20     Vadodara     84
4  105   Ruchi   22  Gandhinagar     96

**Step - 11 : Display the Last Five Records.**

In [ ]:
#Using head() to print the last five records.

df_csv.tail()

    ID     Name  Age         City  Marks
1  102    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

**Step - 12 : Display Dataset of Information.**

In [ ]:
#Using info() to display the characteristics of the DataFrame.

df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Age     6 non-null      int64
 3   City    6 non-null      object
 4   Marks   6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

**Step - 13 : Display Statistical Summary.**

In [ ]:
#Using describe() to display the Satistical Values of each columns of the DataFrame.

df_csv.describe()

               ID        Age      Marks
count    6.000000   6.000000   6.000000
mean   103.500000  19.333333  85.500000
std      1.870829   3.204164   9.565563
min    101.000000  13.000000  74.000000
25%    102.250000  20.000000  77.250000
50%    103.500000  20.000000  86.500000
75%    104.750000  20.750000  93.500000
max    106.000000  22.000000  96.000000

**Step - 14 : Display Dataset Shape.**

In [ ]:
#By using shape display the number of rows and columns in the DataFrame.

df_csv.shape

(6, 5)

**Step - 15 : Display Column Name.**

In [ ]:
##By using columns display the names of columns in the DataFrame.

df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step - 16 : Display Data Types.**

In [ ]:
##By using dtypes display the datatype of each columns.

df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step - 17 : Check for any missing value.**

In [ ]:
#Verifying that the DataFrame is not null and calculating the number of null values in a particular column.

df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step - 18 : Display a single column.**

In [ ]:
#Displaying the values of a single column.

df_csv["Name"]

0      Rahul
1      Priya
2      Rajan
3     Krisha
4      Ruchi
5    Dhruvil
Name: Name, dtype: object

**Step - 19 : Display multiple columns.**

In [ ]:
#Displaying the values of multiple columns.

df_csv[["Name", "Marks"]]

      Name  Marks
0    Rahul     89
1    Priya     95
2    Rajan     75
3   Krisha     84
4    Ruchi     96
5  Dhruvil     74

**Step -20 : Filter Records.**

In [ ]:
#Filtering the records to display the desired output.

df_csv[df_csv["Marks"] > 80]

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     89
1  102   Priya   21    Ahemdabad     95
3  104  Krisha   20     Vadodara     84
4  105   Ruchi   22  Gandhinagar     96

**Step - 21 : Calculate the average marks.**

In [ ]:
#Display the average marks of students.

df_csv["Marks"].mean()

np.float64(85.5)

**Step - 22 : Sort Data.**

In [ ]:
#Sorting the students on the basis of marks in descending order.

df_csv.sort_values(by="Marks", ascending=False)

    ID     Name  Age         City  Marks
4  105    Ruchi   22  Gandhinagar     96
1  102    Priya   21    Ahemdabad     95
0  101    Rahul   20        Surat     89
3  104   Krisha   20     Vadodara     84
2  103    Rajan   13        Surat     75
5  106  Dhruvil   20        Surat     74